ignores:
  - depcheck
  - declapract
  - declapract-typescript-ehmpathy
  - rhachet-roles-bhrain # self-reference for portable skill dispatch
  - "@commitlint/config-conventional"
  - serverless-prune-plugin
  - husky
  - if-env
  - rhachet
  - "@tsconfig/node20"
  - "@tsconfig/strictest"
  - "@biomejs/biome"
  - esbuild-register
  - "@swc/core"
  - "@swc/jest"
  - tsc-alias
  - tsx
  - "@src/*"
  - "@src/.*"
  - yalc
  - "@anthropic-ai/claude-code"
  - rhachet-roles-bhrain
  - rhachet-roles-bhuild
  - rhachet-roles-ehmpathy
  - rhachet-brains-anthropic
