import { DomainLiteral } from 'domain-objects';

import { BrainArch1ToolCall } from './BrainArch1ToolCall';

/**
 * .what = role of the message sender in the conversation
 * .why = llm apis require role to understand context
 */
export type BrainArch1SessionMessageRole =
  | 'system'
  | 'user'
  | 'assistant'
  | 'tool';

/**
 * .what = captures a single message in the brain's conversation context
 * .why = enables building and managing the conversation history for llm calls
 */
export interface BrainArch1SessionMessage {
  /**
   * role of the message sender
   */
  role: BrainArch1SessionMessageRole;

  /**
   * text content of the message (null if tool-only response)
   */
  content: string | null;

  /**
   * tool calls generated by assistant (null if no tools called)
   */
  toolCalls: BrainArch1ToolCall[] | null;

  /**
   * tool result callId this message responds to (only for role=tool)
   */
  toolCallId: string | null;
}

export class BrainArch1SessionMessage
  extends DomainLiteral<BrainArch1SessionMessage>
  implements BrainArch1SessionMessage
{
  public static nested = {
    toolCalls: BrainArch1ToolCall,
  };
}
