import { DomainLiteral } from 'domain-objects';

/**
 * .what = captures a single tool invocation request from the llm
 * .why = enables routing and execution of tool calls generated by the brain
 */
export interface BrainArch1ToolCall {
  /**
   * unique identifier for this tool call (used to match with result)
   */
  id: string;

  /**
   * name of the tool to invoke
   */
  name: string;

  /**
   * input arguments for the tool (parsed json object)
   */
  input: Record<string, unknown>;
}

export class BrainArch1ToolCall
  extends DomainLiteral<BrainArch1ToolCall>
  implements BrainArch1ToolCall {}
